In [21]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display
import io

# Widget para la carga del archivo
upload = widgets.FileUpload(accept='.csv', multiple=False)

# Variable global para almacenar el DataFrame
dafaframe_total = pd.DataFrame()

def on_upload_change(change):
    global dafaframe_total
    # Verificar si hay archivos cargados
    if upload.value:
         # Obtener el contenido del archivo cargado
        uploaded_file = upload.value[0]  # Acceder al primer elemento de la tupla
        content = uploaded_file['content']
        
        # Convertir el contenido de memoryview a bytes y despues a string
        content_bytes = content.tobytes()
        
        content_str = content_bytes.decode('utf-8')
        dafaframe_total = pd.read_csv(io.StringIO(content_str), delimiter=';')
        
    else:
        print("No se ha cargado ningún archivo")

# Observador del cambio de archivo cargado
upload.observe(on_upload_change, names='value')

# Mostrar el widget
display(upload)

FileUpload(value=(), accept='.csv', description='Upload')

In [23]:
dafaframe_total

,Timestamp,Attention,Meditation,Delta,Theta,LowAlpha,HighAlpha,LowBeta,HighBeta,LowGamma,HighGamma,Signal,Key
0,54127,84,48,25253,14225,3441,4172,1881,9630,6863,5745,0,LButton
1,55056,78,60,4946,5021,8879,13002,879,6367,4314,3150,0,NaN
2,56038,66,75,102896,14838,12817,8565,2890,14525,9144,23072,0,NaN
3,57043,61,87,57763,12541,6173,5120,3238,10192,9048,6663,0,NaN
4,58203,37,84,21560,74162,11297,9217,4844,1945,2644,1678,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
721,348567,81,37,4088,13782,756,5536,7114,24230,12942,14061,0,Right
722,355018,84,20,3490,13947,2299,2051,3315,22789,17542,9966,0,Right
723,358034,84,38,3619,8525,5623,6665,5345,31352,22837,12553,0,Right
724,361108,83,51,116972,5464,1405,6395,2285,7186,5351,1219,0,Right
725,362635,57,44,120133,59585,2946,1584,5438,6210,3140,1884,0,NaN